pie.bert.tracker.domain.category:
  maxCodeLength: 3
  minCodeLength: 2
  maxNameLength: 120
  minNameLength: 3
  maxDescriptionLength: 1000
  minDescriptionLength: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/tracker?serverTimezone=Europe/Warsaw
    username: root
    password: pass1234
